### ISSUE TITLE
Add release process support

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/login-service#3]
Release process support is missing, let's consider using the same setup as other AbsaOSS tools.

Perhaps get inspired by https://github.com/AbsaOSS/spark-partition-sizing
 - https://github.com/AbsaOSS/spark-partition-sizing/pull/39 +  https://github.com/AbsaOSS/spark-partition-sizing/pull/45

**Comment by Zejnilovic** [comment]
This is not a library, so I would opt against pushing to maven central. I would just drop the files to GitHub release.
