### ISSUE TITLE
Config using native Scala types

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/login-service#44]
Currently, the configuration of the application is governed by native SpringBoot Configuration binding. This works, but results in Java-like structures (Arrays instead of Lists, nulls instead of Options). This complicates scala-based tests where deep structure comparisons had to be made by custom code.

The object of this issue is to research if we could have the config objects represented increasingly (or ideally fully) by native Scala classes (case classes, Lists/Seqs, Maps, Options.

## Possible solutions
1. Finding a way to achieve this using SpringBoot config directly (unknown if feasible, but preferred)
2. Considering using another config framework that would easily integrate with rest of the SpringBoot app design ([circle](https://github.com/circe/circe-config)? [typesafe config](https://github.com/lightbend/config)?
3. Providing an idiomatic-Scala layer over the current Java-like config layer

**Comment by TheLydonKing** [comment]
Looking into [PureConfig ](https://pureconfig.github.io/)Library for this implementation (https://pureconfig.github.io)
