### ISSUE TITLE
Consider allowing expiring token renewal

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/login-service#54]
## Background
TODO 

@fateeand @jakipatryk 

## Feature
A description of the requested feature.

## Example [Optional]
A simple example if applicable.

## Proposed Solution [Optional]
Solution Ideas:
1. 
2. 
3.

**Comment by kevinwallimann** [comment]
https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

**Comment by dk1844** [comment]
solved by #75
